#!/bin/bash
PLATFORMS=$1
COMMIT_MESSAGE=$2
ALIYUN_REGISTRY=$3
ALIYUN_NAME_SPACE=$4
COMMIT_MESSAGE=$5

for PLATFORM in $(echo $PLATFORMS | tr ',' '\n'); do
  plat="${PLATFORM#*/}"
  docker pull  --platform $PLATFORM  ${ALIYUN_REGISTRY}/${ALIYUN_NAME_SPACE}/${COMMIT_MESSAGE}_${plat}
done
