apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: gproxy-container
          image: {image}
          env:
            - name: GOST_ARGS
              value: "/usr/bin/gost  -L=tcp://:7890/106.55.28.116:7890 -F=http://xxx.xxx.68.185:8118"